spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Finance SaaS
    username: postgres
    password: 09102004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: CLIENT-ID
            client-secret: CLIENT-SECRET
