frontend:
  url: ${FRONTEND_URL}

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_PASSWORD}
            scope:
              - openid
              - profile
              - email
            redirect-uri: ${BACKEND_URL}/login/oauth2/code/google

  # Session configuration
  session:
    timeout: 30m
    cookie:
      name: JSESSIONID
      secure: true # HTTPS
      http-only: true # XSS
      same-site: none # cross-site
      max-age: 1800 # 30 minutes

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: 900000
  refresh-token:
    expiration: 604800000
  cookie:
    secure: true
    same-site: None

server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
        http-only: true
